version: '3.9'
services:
  docker-cra: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    # volumes: 
      #- /home/node/app/node_modules
      #- ./:/home/node/app
    volumes: 
      - type: volume
        target: /home/node/app/node_modules
      - type: bind
        source: ./
        target: /home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes: 
  lh:
    driver: local
