FROM node:alpine
WORKDIR /home/node

USER node
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin
COPY package.json .
RUN yarn install --only=prod
COPY ./ ./

CMD ["yarn", "start"]